import type { Metadata } from "next";
import { Navbar } from "../components/Navbar/Navbar";
import { PageWrapper } from "../components/PageWrapper/PageWrapper";
import { TRPCReactProvider } from "../utils/trpc/react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Suppressed hydration warnings as extensions often add things here */}
      <body suppressHydrationWarning={true}>
        <TRPCReactProvider>
          <Navbar />
          <PageWrapper>{children} </PageWrapper>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
